title: 技术博客
description: 暗场CT | 医学影像重建 | Deep Learning
url: https://changshengfeng.github.io
repository: changshengfeng/changshengfeng.github.io

remote_theme: mmistakes/minimal-mistakes@4.24.0

markdown: kramdown

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# 必须加，否则 GitHub Pages 构建直接失败
paginate: 5
paginate_path: "/page:num/"
