title: "冯昌升的技术博客"
description: "暗场CT | 医学影像重建 | Deep Learning"
url: "https://changshengfeng.github.io"         # 一定要是这个格式（含 https）
repository: "changshengfeng/changshengfeng.github.io"   # ← 关键：指定仓库名
google_analytics: "G-EYFKFRX11M"   # 可选，之后填真实 ID
