title: "技术博客"
description: "暗场CT | 医学影像重建 | Deep Learning"
url: "https://changshengfeng.github.io"
repository: "changshengfeng/changshengfeng.github.io"



remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache


plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "G-EYFKFRX11M"
    anonymize_ip         : false

markdown: kramdown
